### ISSUE TITLE
Allow genuine players to bypass this verification

### ISSUE THREAD

**Issue by misss520** [jonesdevelopment/sonar#165]
### Information

The identities of genuine players are mostly reliable
So there is no need to do this verification
In addition, I hope there are options to adjust the verification after successful verification, such as sending it directly to the login server instead of disconnecting.
I'm looking forward to seeing these features added, it will be very helpful to complete the plugin

### Reason

Some very useful feature improvements

**Comment by jonesdevelopment** [comment]
> such as sending it directly to the login server instead of disconnecting
No possible with the current design — https://discord.com/channels/923308209769426994/1177305423930462248

> there is no need to do this verification
There is no way of identifying an individual player without taking their UUID/username and IP address (I'm storing a combination of the UUID and the IP address in the database)
If your IP or username changes, you must re-verify. Otherwise, bots will bypass.

**Comment by jonesdevelopment** [comment]
> such as sending it directly to the login server instead of disconnecting

As much as I would love this feature, it's not possible with the current design.
Read more: https://discord.com/channels/923308209769426994/1177305423930462248

> there is no need to do this verification

There is no way of identifying an individual player apart from their UUID, username, and IP address (I'm storing a combination of the UUID and the IP address in the database)
If your IP or username changes, you must re-verify. Otherwise, bots will bypass.

**Comment by jonesdevelopment** [comment]
Checking for permissions will also not work since I do not load any permissions during the login checks to avoid any unnecessary RAM/CPU consumption. Imagine 10,000 bots joining the queue and I'd have to check every single one of their perms :/

**Comment by misss520** [comment]
> Checking for permissions will also not work since I do not load any permissions during the login checks to avoid any unnecessary RAM/CPU consumption. Imagine 10,000 bots joining the queue and I'd have to check every single one of their perms :/

Maybe from a performance perspective, what you said does make sense.

**Comment by misss520** [comment]
If these two functions are impossible to implement or are difficult
I want to know why, there is no option in the configuration file to configure the authentication bypass time?

**Comment by misss520** [comment]
If the verification is successful only once, the player is considered not a robot.
Is this approach unsafe?

**Comment by misss520** [comment]
> > such as sending it directly to the login server instead of disconnecting
> 
> As much as I would love this feature, it's not possible with the current design. Read more: https://discord.com/channels/923308209769426994/1177305423930462248
> 
> > there is no need to do this verification
> 
> There is no way of identifying an individual player apart from their UUID, username, and IP address (I'm storing a combination of the UUID and the IP address in the database) If your IP or username changes, you must re-verify. Otherwise, bots will bypass.

Then I can only hope for the possibility of implementation in the future
Thank you for your answer
