### ISSUE TITLE
Feature Request: IPTables support

### ISSUE THREAD

**Issue by msmanui** [jonesdevelopment/sonar#250]
### Information

I've been checking the config and doesnt seem to be mentoning something about firewall block using iptables. 

### Reason

Would not be this more effective to block the IP once it founded that it's a bot? Specially for large massive attacks would be useful. This list could be reset every 24 hours or when the server restart just in case there are some false positives?

**Comment by jonesdevelopment** [comment]
Hey, thanks for the idea, but I don't think IPTables would help block bots that much:

1. Sonar's current blacklist system will become obsolete
2. You will need `root` access to the server in order to perform IPTables/IPSet operations
    - Pterodactyl?
    - Docker containers?
    - Minecraft game server hostings?
3. When am I supposed to run the operations?
    - Every second? Every blacklist?
4. This is not meant to be done by Sonar — I recommend using a 3rd party DDoS protection service like TCPShield or NeoProtect, as they can practically do a much better job at preventing those flood attacks than a Minecraft plugin. What I'm trying to say is that Sonar is not supposed to be handling all those floods, as it does not depend on Sonar if the server is lagging or not, it's the server itself. If the server can't handle these connections, it will lag, not matter what anti-bot you have installed.

**Comment by jonesdevelopment** [comment]
@msmanui I will close this issue because of inactivity. If you need further help, please reopen it or reply to my comment.
