### ISSUE TITLE
Feature Request: Reverse proxy/XDP filtering

### ISSUE THREAD

**Issue by UTrosh** [jonesdevelopment/sonar#296]
### Information

  Make a sonar version that "reverse proxy mode" like infinity filter, and implement xdp filtering

### Reason

Better filtering and protect more server in one time

**Comment by jonesdevelopment** [comment]
Well, this is generally a nice idea, but how am I supposed to *simply make a version of Sonar that does XYZ*? Sonar is a plugin. I'm not fully recoding the entire project just to make it a reverse proxy. It also comes with a lot more challenges. Maybe for Sonar 3.0... but it's out of scope right now, especially because I don't have much time at the moment.

**Comment by jonesdevelopment** [comment]
(eBPF) XDP filtering is not something you can easily implement in Java. AFAIK, you need some custom modules for the Linux kernel, etc.

**Comment by jonesdevelopment** [comment]
If I were to completely recode Sonar, **people will no longer be able to configure it the way they could before.** In-game features and commands would be fully removed, as they wouldn't work anymore.

**Comment by jonesdevelopment** [comment]
@UTrosh If you want, we can continue talking on Discord about this topic. However, I will close this issue as I do not believe this is in-scope for Sonar.
