### ISSUE TITLE
Feature Request: Separate whitelist for bypassing the max online per IP check

### ISSUE THREAD

**Issue by JULJERYT** [jonesdevelopment/sonar#353]
### Information

Hey! I have an idea to add `/sonar whitelist` command 
You could add IP to whitelist and it would skip "Maximum number of players online with the same IP address" check.
(or add this option in the config)

### Reason

This would be useful when I would like to enter the server from three accounts at the same time without changing config

### Additional information

Have a nice day to everyone who sees this :)

**Comment by jonesdevelopment** [comment]
> Hey! I have an idea to add /sonar whitelist command

`/sonar verified add <ip> <username/uuid>` already exist, but it only covers the bot verification.

> You could add IP to whitelist and it would skip "Maximum number of players online with the same IP address" check.

This would require a separate verification system/whitelist just for skipping this one check. You can just adjust the values in the configuration, so I see no reason for me to implement this.

> This would be useful when I would like to enter the server from three accounts at the same time without changing config

Sorry, but I am not going to implement a second, separate whitelisting system for one single check because you don't want to change something in the configuration and reload the plugin. I don't see any good use case for letting specific people join with many accounts at the same time. If you're allowing AFK accounts (or something similar), you should just let everyone use multiple accounts at this point.
